idf_component_register(
    SRCS
        "app_main.c"
        "board.c"
        "wifi_mgr.c"
        "csi_mgr.c"
        "ping_gw.c"
        "espnow_rx_test.c"
        "motion.c"
        "presence.c"
        "link.c"
        "console_cmds.c"
        "devices.c"
        "ble_scan.c"
        "wifi_sniff.c"
        "web_status.c"
    INCLUDE_DIRS "."
    REQUIRES
        "esp_wifi"
        "esp_netif"
        "esp_event"
        "nvs_flash"
        "console"
        "lwip"
        "esp_driver_gpio"
        "esp_timer"
        "bt"
        "esp_http_server"
        "esp_http_client"
        "wifeel_proto"
        "wifeel_csi"
)
